sudo: false
language: node_js
node_js:
- '5'
after_success: ./update-gh-pages.sh
env:
  global:
    secure: 4CeKz3A8/yQTWOM9HUmNWFlfvjZLLdL5sXu0amgvIeXkpqg3JKKXIoR4jIBWnAwZNRbnP02GM/CttPujAp352qjxytpHT3F7dw6LkmL8HEBUZjEGaSSOLBae+LdW1oap7dGUXe5FJpPonUqqzA4ob939cR5NgSdYEV4b8JFQhAiggoXWeoiSXTjgB3fQcooiVcFrLFbrCtuSshupVs6rp0cSRpai3KwWbKOGC8WrTZp+CG176sURFdtXzaEICDfe7TwjhBSnw118d3q91H75LRh2cEqtEAHozyq/pmR+RCrG0aE50A0ZKej8cPcVgcTuX7cssiw8B0x9BoUiTqO0nZj6EZ2AiSC2xcRzIzkLezb+QeKKzazCSHAxQ0hA9bmq/P/xTULp3QO+JdAxX+RO1103RatljJShP1oJbtGC2IE4Qe4Y4dQf7PUz5UP+iwd/zswBejzLQxIIdnhWzWn88ymIEhsaX5k8tTB1IUjo0zbAusYyqRP8OmrIRigMCmw0tGHwA71+Z/h9xoe5VNO75K3lahM4cETrJZ3er9VelznLnyQC6ENbtGaOk4PcoGKhNhguLhQM1zglcr8c9lMrPHDr+C/e75ui8/KWp1i/BTVsf/hV5EW2hwiSpDCJ7+NIKEBfJ2rYVW5PizmPNPJjAKGkI1wt9PoDgZYEiuTz0Ac=
