sudo: false
language: node_js
node_js:
- '5'
after_success: ./update-gh-pages.sh
env:
  global:
    secure: QTHvZycA+KDdxqhsfRe3nKMT2eajxykjFRYHs1Nfdn8H3S08nOH7yALr7v9+H+L84Qpq+reQV12eNQj0ynmI4nztyffbkb2jmVmV7CpM0U1mHeDKW5qB+bmoja24WAc/+5hVAz4leB6w/EtP4zMwhNB39mGpS4kUfrZb3py68JY4QVrBkGSGFDuS8VEpjzwe4oCBdrDl0k3JxayEwBBssfdAZLUHMMvbfK4coDNiqB4DTAD9tOXmKhcMdfENxFcUe5pxgZF3Pm/pfJ2yFl1KXBCQ3DEQ1uTjpzyKgI6853AU8zZNV8bHopyCdvC6Rpx4PWyAnu6dnwXOE/eUMDIYAR2dNJnBqHnI30jTqj6ysrwMhr1MXFVJhZKel6U1mikUDy6EcuHs393oKeTC1LgCRbrAlTq/gSG0T5Xv1UOMf87WzMJjuBFWvCZ5gQnAcCXQ8OhvkVFgotavbHvMGZtyacy3jCEKzLUgcbtDyBaI7X1w8r4rd6mrFXm4tHdSiGqOzz2o7OWCTWA1IrOZ17iVPPk/ZplBqumnBQWU1Sl70QnDvCdimeC9OiKkgZy4TAYc+zXLEmtAq7T5q2I6ARi8EwX8017012bYie/5q6EZPtNbM5hPLWBUdvUP3GVGhTjve7z2IG7hTsrbHlaSWRHtkMr0LRoUTM2vfABI1H3SF/g=
